version: '3'

networks:
  news-network:
    driver: bridge

services:
  server:
    image: nginx:stable-alpine
    container_name: news-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
    networks:
      - news-network

  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    image: 'bitnami/symfony:5.4'
    container_name: news-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/
    environment:
      SYMFONY_PROJECT_NAME: news
    depends_on:
      - database
    networks:
      - news-network

  database:
    image: mysql:8
    container_name: news-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - news-network

  adminer:
    image: adminer
    container_name: news-adminer
    restart: always
    ports:
      - "8081:8081"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: news-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - news-network
  node:
    image: "node:latest"
    container_name: news-node
#    user: "node"
    working_dir: /var/www/
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/var/www/